---

apiVersion: v1
kind: Service
metadata:
  name: auth-db-service
  namespace: auth-ns
spec:
  selector:
    app: auth-db
  clusterIP: None 
  ports:
  - name: auth-db-port
    protocol: TCP
    port: 27017
    targetPort: 27017 

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: auth-statefulset
  namespace: auth-ns
  labels:
    app: auth-db
spec:
  selector:
    matchLabels:
      app: auth-db
  serviceName: auth-db-service
  replicas: 1 
  template:
    metadata:
      labels:
        app: auth-db
    spec:
      containers:
      - name: auth-db-container
        image: mongo:latest 
        resources:
          requests:
            cpu: 200m
            memory: 200Mi 
          limits:
            cpu: 400m 
            memory: 400Mi 
        livenessProbe:
          tcpSocket:
            port: 27017 
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - mongosh
            - --eval
            - db.adminCommand('ping')
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        ports:
        - containerPort: 27017 
          name: auth-db-port
      restartPolicy: Always


---

apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: auth-ns
type: Opaque
data:
  client-secret: cVBVTHBValplOGVFdnFqUXlXVnRMZEY1U0RBQnQzcjJ1MHg4cGRUY3VhSQ==

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  namespace: auth-ns
  labels:
    app: auth
spec:
  selector:
    matchLabels:
      app: auth
  replicas: 1 
  template:
    metadata:
      labels:
        app: auth
    spec:
      initContainers:
      - name: check-mongo
        image: busybox
        command: ['sh','-c', 'until nslookup auth-db-service.auth-ns.svc.cluster.local; do echo waiting for auth-db; sleep 2; done;']
        
      - name: check-kafka
        image: busybox
        command:
        - sh
        - -c
        - |
          until nc -zv kafka-service.kafka-ns.svc.cluster.local 9092; do
            echo "Waiting for Kafka to be ready..."
            sleep 2
          done
        
      containers:
      - name: auth-container
        image: kka01/timeshaasan-auth:latest 
        resources:
          requests:
            cpu: 100m 
            memory: 50Mi 
          limits:
            cpu: 250m 
            memory: 200Mi 
        livenessProbe:
          tcpSocket:
            port: 5001 
          initialDelaySeconds: 10
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /working 
            port: 5001
          initialDelaySeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: DB_URI
          value: mongodb://auth-db-service.auth-ns.svc.cluster.local:27017 
        - name: JWT_EXPIRES_IN
          value: 60d 
        - name: KAFKA_BROKER
          value: "kafka-service.kafka-ns.svc.cluster.local:9092" 
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: client-secret 
        ports:
        - containerPort: 5001 
          name: auth-port
      restartPolicy: Always 

---

apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: auth-ns
spec:
  selector:
    app: auth
  ports:
  - name: auth-port
    protocol: TCP
    port: 5001
    targetPort: 5001 
